example:
  jms:
    username: Sender
    password: somejmspass
    url: somejmsurlfromyml



#Example Config
name: Jonh

names: John, Paul, Ringo

pound_sign: '#'

book:
  author: Joe Buck
  publisher: random house

album:
  author: Jonny Cage

truth: yEs

another_truth: True

more_true: true

false: no #No, false, FALSE

string_val: "This is it's quote"

colon_string: "my coureses: one two three"

include_new_lines: |
  asdf asdf asdf
  asdf adfewf asdf
  asdf ae adfre

ignore_new_lines: >
  this is
  just one long
  string

---
spring:
  profiles: de
example:
  jms:
    username: GERMANGSERNDER